server:
  port: 8080
  mode: debug

database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: "123456"
  dbname: linkit
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

shortlink:
  domain: "http://localhost:8080"
  length: 6
  expiration: 720h # 默认过期时间（30天）

ratelimit:
  enabled: true
  requests: 1000000000000
  duration: 1m